import localFont from 'next/font/local'
import { UserProvider } from "@/context/AuthContext";
import Layout from "@/components/layout/Layout";
import "./globals.css";
import TanstackQueryProvider from '@/components/partials/providers/TanstackQueryProvider';

const yekan = localFont({ src: '../public/fonts/Yekan.ttf' });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="fa" dir="rtl">
      <body className={yekan.className}>
        <UserProvider>
          <TanstackQueryProvider>
            <Layout>
              {children}
            </Layout>
          </TanstackQueryProvider>
        </UserProvider>
      </body>
    </html>
  );
}
